module.exports = {
  preset: "ts-jest",
  testEnvironment: "jsdom", // Use jsdom for DOM and localStorage support
  setupFilesAfterEnv: ["<rootDir>/jest.setup.js"], // Ensure localStorage mock is loaded
  transform: {
    "^.+\\.(ts|tsx)$": "ts-jest",
    "^.+\\.(js|jsx)$": "babel-jest",
  },
  moduleFileExtensions: ["ts", "tsx", "js", "jsx", "json", "node"],
  testPathIgnorePatterns: [
    "/node_modules/",
    "/tests/e2e/", // Ignore all Playwright E2E tests
    "/tests/.*\\.e2e\\.spec\\.[tj]sx?$/",
    "/tests/.*playwright.*\\.spec\\.[tj]sx?$/",
    "/tests/.*Accessibility.*\\.spec\\.[tj]sx?$/",
    "/tests/.*Flow.*\\.spec\\.[tj]sx?$/",
    "/tests/.*badges.*\\.spec\\.[tj]sx?$/",
    "/tests/.*bookmark.*\\.spec\\.[tj]sx?$/",
    "/tests/.*sync.*\\.spec\\.[tj]sx?$/",
    "/tests/.*error.*\\.spec\\.[tj]sx?$/",
    "/tests/.*quiz.*\\.spec\\.[tj]sx?$/",
    "/tests/.*modal.*\\.spec\\.[tj]sx?$/",
    "/tests/.*panel.*\\.spec\\.[tj]sx?$/",
    "/tests/.*Mastery.*\\.spec\\.[tj]sx?$/",
    "/tests/.*Debug.*\\.spec\\.[tj]sx?$/",
    "/tests/.*Toast.*\\.spec\\.[tj]sx?$/",
    "/tests/.*E2E.*\\.spec\\.[tj]sx?$/",
    "/tests/.*Analytics.*\\.spec\\.[tj]sx?$/",
    "/tests/.*describe.*\\.spec\\.[tj]sx?$/",
    "/tests/.*@playwright/test.*\\.spec\\.[tj]sx?$/",
    // Ignore any test file that imports Playwright or uses test.describe (by filename)
    "/tests/appIconAndAvatarFlow.spec.ts$",
    "/tests/errorHandlingAndRecoveryFlow.spec.ts$",
    "/tests/firestoreAndAvatarFlow.spec.ts$",
    "/tests/firestoreQuestionLoadingUI.spec.ts$",
    "/tests/modalsAndBadgesFlow.spec.ts$",
    "/tests/quizMasteryToastDebugFlow.spec.ts$",
    "/tests/quizStartAndUIUpdate.spec.ts$",
    "/tests/syncErrorFlow.spec.ts$",
    "/tests/errorBoundary.advanced.e2e.spec.ts$",
    "/tests/analyticsModalLiveUpdate.spec.ts$",
    "/tests/errorBoundaries.panels.e2e.spec.ts$",
    "/tests/analyticsAndBookmarkSyncFlow.spec.ts$",
    "/tests/analyticsStatsUpdate.spec.ts$",
    "/tests/analyticsModal.e2e.spec.ts$",
    "/tests/noQuestionsPlaceholderUI.spec.ts$",
    "/tests/analyticsModal.advanced.e2e.spec.ts$",
    "/tests/bookmarkSyncToast.spec.ts$",
    "/tests/analyticsFlicker.spec.ts$",
    "/tests/badgesBookmarksAnalyticsFlow.spec.ts$",
    "/tests/analyticsRestartAndTopicChange.spec.ts$",
    "/tests/bookmarkingFlow.spec.ts$",
    "/tests/toastNotificationFlow.spec.ts$",
    "/tests/badgeProgressPanel.advanced.e2e.spec.ts$",
    "/tests/badgeProgressPanel.e2e.spec.ts$",
    "/src/components/__tests__/ErrorBoundary.e2e.spec.ts$",
  ],
  moduleNameMapper: {
    // Mock CSS modules for Jest
    "\\.module\\.css$": "identity-obj-proxy",
    // Mock Firebase modules
    "^../firebase/indexFirebase(\\.js)?$": "<rootDir>/__mocks__/firebase/indexFirebase.js",
    "^../firebase/helpersFirebase(\\.js)?$": "<rootDir>/__mocks__/firebase/helpersFirebase.js",
    // Add mapping for TypeScript utils
    "^../utils/(.*)$": "<rootDir>/src/utils/$1",
  },
};
