name: CI

on:
  push:
    branches: [main, feature/testing-setup, refactor/modularize-app, base-app-fully-featured-2]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install
      - run: npm run lint
      - run: npm run type-check
      - run: npm test
      - run: npm run build
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright asset tests on GitHub Pages
        env:
          PLAYWRIGHT_BASE_URL: https://youngjnick.github.io/Massage-Therapy-FIREBASE-PRO/
        run: npx playwright test e2e/assets-on-production.spec.ts
